### ISSUE TITLE
Questions about Sendy integration

### ISSUE THREAD

**Issue by Planetediscount** [N-Wouda/PS-Sendy#1]
Hello N-Wouda,

Please before i test your module, can you tell me if the customer still go inside Prestashop Database (For Ip, shop id, date add) or if information go only to Sendy.

Also please witch informations is send to Sendy, just email ?

Thanks for work and help

Regards,

**Comment by N-Wouda** [comment]
Hello Planetediscount,

The data will still go into your database, but also be sent to Sendy. This means that, if you decide to no longer use Sendy, you still have all registrations within PrestaShop.

For the free version, only email is shared with Sendy, and name if this is known (_i.e._, if it is a logged in customer). I also made a paid addon with custom fields and csv exports (amongst other things) that's currently in validation; I'll link to it in a few days once it passes validation by PrestaShop.

I hope this answers your questions.

Kind regards,

Niels Wouda

**Comment by Planetediscount** [comment]
Thanks for your answer, that perfect

i just tested in test website, and email go in database but not in sendy.
I tested single store and multistore, fonction to send email is off on shop.
I have insert the url of sendy installation, my url don't have www. but have http://subdomain.domain.fr
i have insert the ID of Sendy List
Prestashop 1.6.1.6 - Sendy lastest version 2.1.1.4

**Comment by Planetediscount** [comment]
I forgot, on Sendy, i have 2 brands

**Comment by N-Wouda** [comment]
Do you have cURL enabled? If not, there should be a warning on the modules screen. 

Do you use a theme other than the default theme? If so, it _might_ be that the newsletter block has a different ID on the front-end. Could you email me these details and the test shop URL (I can imagine you'd not want to disclose publicly) to n.wouda@apium.nl?

**Edit:** I just tested it again on my own test site, and for me it works just fine. Please do email, as I would very much appreciate it if we could resolve this problem for you.

**Comment by N-Wouda** [comment]
Closing this.

The problem was that in Planetediscount's theme, the submit button (default also an HTML button, i.e. `<button>`) was actually a styled `<input>` field. This meant the JavaScript didn't attach a click event to the submit. We solved it, and I'll update the code accordingly.
